Repository Patternslib/Patterns, pull requests merged in 2018-07, with the labels that each got.

#605 Improve pat-autosuggest so that inputs with a max selection size show…
  CHANGES.md
  package.json
  src/pat/auto-suggest/auto-suggest.js
  src/pat/auto-suggest/data.json
  src/pat/auto-suggest/index.html
  src/pat/auto-suggest/select2x2.png
  src/pat/auto-suggest/tests.js
  style/select2x2.png
Labels: review

#606 Do not threat javascript:... href as relative URLs
  src/pat/inject/inject.js
Labels: in progress

#608 Add reverse substring comparison for depends (wichert) fix parser (alex)
  CHANGES.md
  VERSION.txt
  src/lib/depends_parse.js
  src/lib/depends_parse.pegjs
  src/lib/dependshandler.js
Labels: in progress

#609 Propose suggested solution as described in https://github.com/Pattern…
  src/pat/inject/index.html
  src/pat/inject/inject-sources.html
  src/pat/inject/inject.js
Labels: in progress

#610 WIP: Push
  CHANGES.md
  Makefile
  index.html
  package-lock.json
  package.json
  push/.gitignore
  push/.hz/config.toml
  push/.hz/schema.toml
  push/.hz/secrets.toml
  push/README.txt
  push/dist/app.js
  push/dist/index.html
  src/core/push_kit.js
  src/pat/inject/index.html
  src/pat/inject/inject.js
  src/pat/inject/tests.js
  src/patterns.js
  webpack/base.config.js
Labels: hold merge, in progress

#612 first the larger, then the smaller
  src/lib/depends_parse.js
  src/lib/depends_parse.pegjs
Labels: in progress
