Repository Patternslib/Patterns, pull requests merged in 2019-03, with the labels that each got.

#640 Fix pat notification
  CHANGES.md
  package-lock.json
  src/pat/notification/notification.js
  style/patterns.css
Labels: in progress

#641 Update intersection-observer
  package-lock.json
  package.json
Labels: in progress

#642 catch case when post url already has a querystring
  src/pat/inject/index.html
  src/pat/inject/inject-form.html
  src/pat/inject/inject.js
Labels: in progress

#644 Fix .pat-modal inside [data-pat-inject]
  CHANGES.md
  src/core/parser.js
Labels: Pattern modal, ready

#648 Support the `first-day` parameter
  CHANGES.md
  package-lock.json
  src/pat/date-picker/date-picker.js
  src/pat/date-picker/documentation.md
  src/pat/date-picker/index.html
  src/pat/date-picker/tests.js
  src/pat/datetime-picker/datetime-picker.js
  src/pat/datetime-picker/documentation.md
  src/pat/datetime-picker/index.html
  src/pat/datetime-picker/tests.js
Labels: in progress

#646 Optimize the argParserParse function
  src/core/parser.js
Labels: Performance, ready
